### ISSUE TITLE
Month is displayed as a digit, not string

### ISSUE THREAD

**Issue by Nepalec** [marosseleng/compose-material3-datetime-pickers#147]
![image](https://github.com/marosseleng/compose-material3-datetime-pickers/assets/3699480/756b314a-d95e-4edc-b22e-6d45621e3528)

**Comment by marosseleng** [comment]
Hi, thanks for the issue. To format month/year, I am using [system-provided formatters](https://github.com/marosseleng/compose-material3-datetime-pickers/blob/4fdfa64ce22ccea2865151c9a520c4c6ef88d498/datetimepickers/src/main/java/com/marosseleng/compose/material3/datetimepickers/date/domain/Extensions.kt#L28). I noticed that on some Locales this problem occurs, but as of now, the fix isn't planned.

This library should slowly become deprecated in favor of Google's official dialogs introduced in Material3-1.1.0 I think.
