### ISSUE TITLE
Add support for DatepickerMode for selecting years and months as per requirements

### ISSUE THREAD

**Issue by v1kasjaiswal** [marosseleng/compose-material3-datetime-pickers#150]
Datepicker can have different modes as,
Mode.Year -> It will allow user to select only between year ranges
Mode.Month -> It will allow user to select only between month ranges
Mode.MonthYear -> It will allow user to select both month and year ranges but not date.

**Comment by marosseleng** [comment]
Hello, thank you for the issue. This project is no longer maintained in favor of `DatePicker` & rest introducted in compose material3 library.
