### ISSUE TITLE
minSdkVersion 26 too restrictive

### ISSUE THREAD

**Issue by Tgo1014** [marosseleng/compose-material3-datetime-pickers#30]
Having 26 as min version is very restrictive. From my experience, 21 or at maximum 23 is widely used for the minSdkVersion. It's a pity to limit such a useful library to such a high minSdkVersion.
Is the reason to use 26 because of the usage of the most recent Java time APIs? If so, would using [desugaring](https://developer.android.com/studio/write/java8-support) or maybe migrating to [ThreeTen](https://github.com/JakeWharton/ThreeTenABP) be a possibility?

Thanks for the great work!

**Comment by marosseleng** [comment]
Hi, it is indeed due to java.time APIs. In the beginning, the code was part of my private project with minSdk 26, thus originally it was not necessary having it anywhere lower.

Incorporating desugaring is definitely planned, but didn't have much priority due to the reason above.
