### ISSUE TITLE
Swipe to change month

### ISSUE THREAD

**Issue by HairyOtter07** [marosseleng/compose-material3-datetime-pickers#39]
I had at one point considered making my own material 3 datetime dialogs library when I found this, which is pretty much exactly what I was looking for.

One of the things in the Material 3 spec for modal date pickers is the ability to swipe horizontally to switch months, and I was wondering if you planned to implement that? Maybe with a paging library like Accompanist?

**Comment by marosseleng** [comment]
Hi, thanks for the input. Although currently I don't have the swipe support planned, I may put it in a future milestone.

Could you please attach a link to the specs with horizontal swipes discussed in this issue? Thank you.

**Comment by HairyOtter07** [comment]
Yeah, of course.

On the material3 date picker guidelines page (https://m3.material.io/components/date-pickers/guidelines), under modal date pickers, there's a line that says "To navigate across months, swipe horizontally"

**Comment by marosseleng** [comment]
Thank you! I somehow missed that paragraph.
I'll have a look at implementing that.
