### ISSUE TITLE
Missing option to disable some days and display different text style

### ISSUE THREAD

**Issue by davidkocnar** [marosseleng/compose-material3-datetime-pickers#96]
There is no support for disabled days, e.g. for weekends. 
Also, there should be an option to define custom text styles for days (numbers).

**Comment by marosseleng** [comment]
Hi, thanks for the issue.

As for disabled days, that is correct, there is no support for disabled days.

As for days text style option, there is `DatePickerTypography.day` property, that should do the trick, with several options for color settings in `DatePickerColors` (`monthDay*LabelTextColor` & `todayLabelTextColor`).

> [customization docs for datepicker](https://github.com/marosseleng/compose-material3-datetime-pickers/blob/main/docs/datepicker/README.md#customization)

For instance, changing text style to display large:
```kotlin
DatePickerDialog(
    //...
    typography = DatePickerDefaults.typography(
        day = MaterialTheme.typography.displayLarge
    )
)
```
produces this:
![image](https://user-images.githubusercontent.com/9325961/225351586-650c9c2c-8f5c-4fb6-9095-e213b8c1fca1.png)

Hope this helps.
